apiVersion: v1
kind: Pod
metadata:
  name: mariadb-pod
  labels:
    app: mariadb-pod
spec:
  containers:
    - name: mariadb
      image: mariadb:10.6.4-focal
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: environment-data
              key: mysql_root_password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: environment-data
              key: mysql_database
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: environment-data
              key: mysql_user
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: environment-data
              key: mysql_password
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: shared
          mountPath: /var/lib/mysql
  volumes:
  - name: shared
    hostPath:
      path: /data
      type: Directory