services:
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=dGE9iy71a18xRbeNd6RCl2EKhqn656Oj
      - MYSQL_DATABASE=classroom_manager
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=OTIsxb71HcC0WyA1UPNIzcvuMJ1Xu6NJ
    ports:
      - 3306:3306
volumes:
  db_data: