apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-api
  labels:
    app: tech-challenge-api
spec:
  template:
    metadata:
      name: tech-challenge-api
      labels:
        app: tech-challenge-api
    spec:
      containers:
      - name: tech-challenge-api-container
        image: joohnsro/tech-challenge-api:1.18
        env:
          - name: MARIADB_HOST
            valueFrom:
              configMapKeyRef:
                name: environment-data
                key: mysql_host
          - name: MARIADB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: environment-data
                key: mysql_database
          - name: MARIADB_USER
            valueFrom:
              configMapKeyRef:
                name: environment-data
                key: mysql_user
          - name: MARIADB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: environment-data
                key: mysql_password
        ports:
          - containerPort: 3000
        resources:
          requests:
            cpu: 1m
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge-api